### ISSUE TITLE
Dependency detected but not installed

### ISSUE THREAD

**Issue by eps1lon** [microsoft/DefinitelyTyped-tools#422] opened 2022-03-29 15:39 UTC
Example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59519 (failing in https://github.com/DefinitelyTyped/DefinitelyTyped/runs/5726980310?check_suite_focus=true)

`styled-components` was correctly identified to depend on `react-native`. However, dependencies of `styled-components` weren't installed so tests are failing.

**Comment by eps1lon** [comment] 2022-04-13 07:21
Also blocking https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59691

**Comment by reichhartd** [comment] 2022-04-23 10:33
Duplicate of https://github.com/microsoft/DefinitelyTyped-tools/issues/413

**Closed** 2022-09-27 17:38 UTC
Labels: duplicate
